### ISSUE TITLE
RFI

### ISSUE THREAD

**Issue by codepologist** [eugenesachez/Ionic-Doc#1]
Hi there,

Is this suppose to be copied into wamp server for it to load on the browser?

regards,
OMBU

**Comment by eugenesachez** [comment]
Not necessarily, just install ionic on your computer and replace the www folder contents with the files I uploaded on github.
here is the link to installation https://ionicframework.com/getting-started/

**Comment by codepologist** [comment]
Thanks for your swift response... Actually i do already have ionic and it's repositories installed using the CLI (npm) but i didn't know i had to replace the www folder with the one you put up here... Thanks buddy!
